[TW-03] add TextGradient component
serudda/twon.app pull request #7
Opened 2023-04-30 03:32 UTC by Zyruks

## Changes Made 🎉

- [X] feat: added new feature to improve user experience
- [ ] fix: corrected a bug with login functionality
- [ ] refactor: improved code readability and organization
- [ ] docs: updated README with new instructions
- [ ] chore: updated dependencies and configuration files

### Describe Changes

This pull request introduces a new feature - the TextGradient component - which allows for text to be displayed with a gradient background. 

The component includes properties for controlling the gradient direction, text size, and color variants.

In addition, this commit updates the index.ts file to export the new TextGradient component.

## Related Issue(s)

- #3 

## Visuals (Optional)
![image](https://user-images.githubusercontent.com/14036522/235334205-91bdf7cb-a4d7-4a81-bd6b-dd841f2888e8.png)

![image](https://user-images.githubusercontent.com/14036522/235334170-4345e8f7-12fe-482d-a56e-f5572d214f6e.png)

## Checklist ✅

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2023-04-30 20:32 UTC, serudda requested changes

2023-04-30 20:32 UTC, serudda commented on apps/nextjs/src/components/TextGradient/TextGradient.tsx
> +}
Te recomiendo que mires como se hace en reward-system, por ejemplo Button o Tag... tu creas un enum, y despues mapeas ese enum con un objeto el cual es el encargado de asignar las classes

2023-04-30 20:32 UTC, serudda commented on apps/nextjs/src/components/TextGradient/TextGradient.tsx
> +}
Te recomiendo que mires como se hace en reward-system, por ejemplo Button o Tag... tu creas un enum, y despues mapeas ese enum con un objeto el cual es el encargado de asignar las classes

2023-04-30 20:32 UTC, serudda commented on apps/nextjs/src/components/TextGradient/TextGradient.tsx
> +}
Esto no es buena practica... ya que tendrias que contemplar N tags de html... en este caso es mejor aceptar una prop children, y dejar que pase cualquier cosa

2023-04-30 20:32 UTC, serudda commented on apps/nextjs/src/components/TextGradient/TextGradient.tsx
> +}
Te recomiendo que mires como se hace en reward-system, por ejemplo Button o Tag... tu creas un enum, y despues mapeas ese enum con un objeto el cual es el encargado de asignar las classes

2023-04-30 20:32 UTC, serudda commented on apps/nextjs/src/components/TextGradient/TextGradient.tsx
> + */
No es necesario este comment

2023-04-30 20:32 UTC, serudda commented on apps/nextjs/src/components/TextGradient/TextGradient.tsx
> +};
```suggestion
  return (
    <HtmlTag
      className={`
      ${defaultProperties}
      ${gradientDirection}
      ${textVariant}
      ${textSizeClass}
      `}
    >
      {children}
    </HtmlTag>
  );
};
```

2023-04-30 22:08 UTC, Zyruks commented on apps/nextjs/src/components/TextGradient/TextGradient.tsx
> + */
Listo.

2023-05-01 04:44 UTC, Zyruks commented on apps/nextjs/src/components/TextGradient/TextGradient.tsx
> +}
done

2023-05-01 04:47 UTC, Zyruks commented on apps/nextjs/src/components/TextGradient/TextGradient.tsx
> +}
![image](https://user-images.githubusercontent.com/14036522/235408092-a845f24b-d59e-4b64-a58b-62e2f5b89c53.png)

Listo los cambios de textVariants ahora nombrado Variant y GradientVariant.

2023-05-01 04:50 UTC, Zyruks commented on apps/nextjs/src/components/TextGradient/TextGradient.tsx
> +}
![image](https://user-images.githubusercontent.com/14036522/235408303-4ebfd7fb-9cd3-431e-836b-c590e6227050.png)Eliminado y ahora pasamos children.

Esto me crea una duda:

Ahora necesito un div para contener cualquier elemento que se pase como children y ese hijo o hijos van a heredar las propiedades del div contenedor.

Estuve pensando en una forma de pasar las clases a los children y usar un fragment en vez del div, pero podría complicar un poco el componente.

2023-05-01 04:51 UTC, Zyruks commented on apps/nextjs/src/components/TextGradient/TextGradient.tsx
> +}
![image](https://user-images.githubusercontent.com/14036522/235408416-b5f55086-a61b-4986-837b-ab7eb205543d.png)

Listo los cambios de GradientDirections.

2023-05-01 04:51 UTC, Zyruks commented on apps/nextjs/src/components/TextGradient/TextGradient.tsx
> + */
Eliminado.

2023-05-01 04:53 UTC, Zyruks commented on apps/nextjs/src/components/TextGradient/TextGradient.tsx
> +};
![image](https://user-images.githubusercontent.com/14036522/235408482-cd15f8f2-1be6-4bac-a008-0627a5245bf1.png)

Listo el cambio pero me genero una duda que esta [aqui](https://github.com/serudda/twon.app/pull/7#discussion_r1181389416)

2023-05-01 05:03 UTC, Zyruks commented on apps/nextjs/src/components/TextGradient/TextGradient.tsx
> +}
## Note:
Añadiendo a la duda que tengo, que he encontrado un problema relacionado con el div que contiene las clases y sus hijos que van a heredar estas propiedades. Si este div contiene varios textos y uno de ellos es más largo que los demás, es posible que el texto principal se vea como si no tuviera el efecto degradado y solo se muestre un color plano, tal y como se muestra en la imagen adjunta:

![image](https://user-images.githubusercontent.com/14036522/235409039-94e1983c-1596-495d-81c5-418918dc3ce5.png)


La solución que propongo para este problema es asignar las clases a cada hijo directo del componente en lugar de asignarlas al div contenedor.

2023-05-01 05:43 UTC, Zyruks commented on apps/nextjs/src/components/TextGradient/TextGradient.tsx
> +}
### Esta es la solución a la que llegue:
![image](https://user-images.githubusercontent.com/14036522/235412112-de9afd29-5a56-4d58-a55f-7f94e815ac59.png)

De esta manera cada children se le pasarán las classes y no sucede el error de más arriba, aparte así no se necesita tener el elemento dentro de un div contenedor

![image](https://user-images.githubusercontent.com/14036522/235411455-be948e29-8039-4bdc-94b3-7f4d6042f31f.png)

## Explicación:

Lo que hago es iterar sobre cada hijo del componente utilizando la función `React.Children.map()`.
 
En cada iteración, compruebo si el hijo es un elemento válido de React utilizando la función `React.isValidElement()`. Si es así, compruebo si el hijo es también un elemento válido del tipo TextGradientProps.
 
Si el hijo cumple estas dos condiciones, lo clono utilizando la función `React.cloneElement()` y le añado la prop `className` con las clases que se han pasado al componente. De esta manera, cada hijo tendrá las clases necesarias para que el efecto degradado se aplique correctamente.

2023-05-01 05:56 UTC, Zyruks reviewed
.

2023-05-01 06:02 UTC, Zyruks commented on apps/nextjs/package.json
Tengo mis dudas de si esta es la forma correcta de agregar dependencias en el monorepo.

2023-05-02 09:20 UTC, Zyruks commented on apps/nextjs/src/components/TextGradient/TextGradient.tsx
> +}
Modifique este approach de usar variantes para darle al developer mas flexibilidad a la hora de crear su text gradient.

### Podemos agregar solo el gradientStartColor
![Code_aRtZiWU4JI](https://user-images.githubusercontent.com/14036522/235627283-cdd8b503-dbfc-45ea-aa6c-54b80811d0f8.gif)

![image](https://user-images.githubusercontent.com/14036522/235627450-efda35fc-992c-408a-b150-95190c2874eb.png)

## agregando un color final(End Color)
![Code_LFWwKvPq8b](https://user-images.githubusercontent.com/14036522/235627654-ad2e94f4-5965-4ba6-9633-d7dcde82a86b.gif)

![image](https://user-images.githubusercontent.com/14036522/235627827-7b7b23c9-7933-4e8b-90a8-d75eb0205d7a.png)

## Ahora podemos tener un color medio
![Code_bEw3iRhLQ5](https://user-images.githubusercontent.com/14036522/235628432-328e249d-cc65-4cbd-8cce-ad81c40f3d86.gif)

![image](https://user-images.githubusercontent.com/14036522/235628111-a4d1ad07-fae2-415f-a0fe-c2f4b064d4af.png)

2023-05-02 09:30 UTC, Zyruks commented
## New feature

Podemos mover la posicion de cada color con el prop

`startColorStop` para mover el `gradientStartColor`
`viaColorStop` para mover el `gradientViaColor`
`endColorStop` para mover el `gradientEndColor`

![image](https://user-images.githubusercontent.com/14036522/235629435-11c1186d-fc18-4c32-afc1-e5e8a51e4045.png)

![image](https://user-images.githubusercontent.com/14036522/235630844-43fc9898-8357-4070-bd99-b0e846dcad61.png)

2023-05-04 05:46 UTC, serudda approved these changes

2023-05-04 05:47 UTC, merged