[TW-04] add DottedBackground component
serudda/twon.app pull request #8
Opened 2023-04-30 06:09 UTC by Zyruks

## Changes Made 🎉

- [X] feat: added new feature to improve user experience
- [ ] fix: corrected a bug with login functionality
- [ ] refactor: improved code readability and organization
- [ ] docs: updated README with new instructions
- [ ] chore: updated dependencies and configuration files

### Describe Changes

Added a new component called `DottedBackground` that displays a dot background with a radial mask. This component accepts several props to customize the dots' color, size, and separation, as well as the transparency of the mask.

## Related Issue(s)

- #4 

## Visuals (Optional)

### Visual Examples of `DottedBackground` Changes
![image](https://user-images.githubusercontent.com/14036522/235338218-f1a927be-08d6-4ecb-8a66-a884b43c4b6d.png)

### Bigger dots and separation 
![image](https://user-images.githubusercontent.com/14036522/235338251-b435df8c-f985-47cb-b399-41651f91a3e9.png)

## Notes:
### Why this approach

The reason why the style attribute is used instead of extending Tailwind classes to customize the `DotBackground` component is because Tailwind classes are pre-defined sets of styles that are optimized for creating common styles quickly. While you can extend Tailwind classes to add your own custom styles, this method may not be practical for all use cases. For example, changing the dot separation, dot color, radial transparency, and dot size are all highly specific and custom changes that may not be easily achievable using Tailwind classes alone.

In such cases, the style attribute allows you to define styles directly on the element, which provides more flexibility in creating custom styles. By defining the styles directly on the component using the style attribute, you can easily make highly specific changes like the ones mentioned above without worrying about the global impact of extending Tailwind classes. This approach ensures that the styles only apply to the specific component, providing a more focused and targeted solution.

### Usage

When using the `DottedBackground` component inside a container, it is important to make sure that any other children elements within the container have a z-index value greater than zero. This is because the `DottedBackground` component creates a masked effect using a radial gradient, which can cause other elements to be hidden if they have a z-index value of zero or lower.

In the given example, the z-10 class has been added to each child element to ensure that they have a z-index value greater than zero. This will ensure that the `DottedBackground` component appears behind the other content within the container, and that the content is not hidden by the masked effect.

## Checklist ✅

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2023-04-30 20:29 UTC, serudda requested changes

2023-04-30 20:29 UTC, serudda commented on apps/nextjs/src/components/DottedBackground/DottedBackground.tsx
> +}
Me generar ruido un enum tan largo... ademas que pasa si quiere agregar "35%"? empezaria a agregar mas opciones muy puntuales.

No es mejor, dejarle que ponga el valor abiertamente? Probar algo como:

`<DottedBackground radialTransparency={30} ... />`

ademas para simplificar el naming, podriamos nombrar la prop solo "transparency".

2023-04-30 20:29 UTC, serudda commented on apps/nextjs/src/components/DottedBackground/DottedBackground.tsx
> +}
que pasa si quiero un color como: pink... o amarilloso? Hay manera de dejar un poco más abierto esto?

2023-04-30 20:29 UTC, serudda commented on apps/nextjs/src/components/DottedBackground/DottedBackground.tsx
> +}
Creo que es mas sencillo transformar esto en tamanos: 
xs, sm, md, lg

o

estrecho, angosto, amplio, etc

2023-04-30 20:29 UTC, serudda commented on apps/nextjs/src/components/DottedBackground/DottedBackground.tsx
> +}
Igual, jugar con tallas: 2xs, xs, sm, md, lg, xl

2023-04-30 20:29 UTC, serudda commented on apps/nextjs/src/components/DottedBackground/DottedBackground.tsx
> +interface DotBackgroundProps {
```suggestion
interface DottedBackgroundProps {
```

Se sugiere mismo nombre que el Componente + Props

2023-04-30 20:29 UTC, serudda commented on apps/nextjs/src/components/DottedBackground/DottedBackground.tsx
> +   * Use DotsSeparation enum for valid values.
Esta linea de comment no es necesaria... solo con una descripcion es suficiente.

2023-04-30 20:29 UTC, serudda commented on apps/nextjs/src/components/DottedBackground/DottedBackground.tsx
> +   * Use DotColors enum for valid values.
Esta linea de comment no es necesaria... solo con una descripcion es suficiente.

2023-04-30 20:29 UTC, serudda commented on apps/nextjs/src/components/DottedBackground/DottedBackground.tsx
> +   * Use RadialTransparency enum for valid values.
Esta linea de comment no es necesaria... solo con una descripcion es suficiente.

2023-04-30 20:29 UTC, serudda commented on apps/nextjs/src/components/DottedBackground/DottedBackground.tsx
> +   *Use DotsSizeRange enum for valid values.
Esta linea de comment no es necesaria... solo con una descripcion es suficiente.

2023-04-30 20:29 UTC, serudda commented on apps/nextjs/src/components/DottedBackground/DottedBackground.tsx
> +}) => {
```suggestion
export const DottedBackground = ({
  dotsSeparation = DotsSeparation.fifteen,
  dotsColors = DotColors.gray20,
  radialTransparency = RadialTransparency.sixty,
  dotsSize = DotsSizes.one,
}: DotBackgroundProps) => {
```

2023-04-30 20:29 UTC, serudda commented on apps/nextjs/src/components/DottedBackground/DottedBackground.tsx
> +}) => {
No recuerdo la explicacion, pero un amigo en la oficina me enseno que con este formato no tendrias inconvenientes con algunos Types

2023-04-30 20:29 UTC, serudda commented on apps/nextjs/src/components/DottedBackground/DottedBackground.tsx
> +  };
Buscar la alternativa con TailwindCSS

2023-04-30 20:29 UTC, serudda commented on apps/nextjs/src/components/DottedBackground/DottedBackground.tsx
> +   */
No es necesario este comment... mirar ejemplo dentro de reward system, capaz un comment mas sencillo

2023-04-30 20:36 UTC, Zyruks commented
Thanks for the review, working on a solution.

2023-05-01 07:14 UTC, Zyruks commented on apps/nextjs/src/components/DottedBackground/DottedBackground.tsx
> +}
![image](https://user-images.githubusercontent.com/14036522/235421356-29b2fe0f-812b-40ec-b9b0-232cb9552b1e.png)

Listo este apartado

2023-05-01 07:14 UTC, Zyruks commented on apps/nextjs/src/components/DottedBackground/DottedBackground.tsx
> +}
![image](https://user-images.githubusercontent.com/14036522/235421412-ff05c273-d2e9-416e-bd63-92d0ffa4dc11.png)

Listo

2023-05-01 07:14 UTC, Zyruks commented on apps/nextjs/src/components/DottedBackground/DottedBackground.tsx
> +interface DotBackgroundProps {
Arreglado también esta parte.

2023-05-01 07:15 UTC, Zyruks commented on apps/nextjs/src/components/DottedBackground/DottedBackground.tsx
> +   * Use RadialTransparency enum for valid values.
Done

2023-05-01 07:15 UTC, Zyruks commented on apps/nextjs/src/components/DottedBackground/DottedBackground.tsx
> +   *Use DotsSizeRange enum for valid values.
Done

2023-05-01 07:16 UTC, Zyruks commented on apps/nextjs/src/components/DottedBackground/DottedBackground.tsx
> +}) => {
![image](https://user-images.githubusercontent.com/14036522/235421572-25ed0694-daf5-4391-8df6-92e3fd7e5130.png)

Listo, ya use el formato que me enseña para evitar problemas a futuro.

2023-05-01 07:18 UTC, Zyruks commented on apps/nextjs/src/components/DottedBackground/DottedBackground.tsx
> +  };
Entonces, como hemos discutido anteriormente, hemos llegado a la conclusión de que no podemos utilizar las clases de TailwindCSS para manejar las props que necesitamos en nuestro componente. Generar tantas clases para cada posible combinación de props sería muy problemático y aumentaría el tamaño del archivo de estilos de manera innecesaria.

En cuanto al maskImage, hemos visto que existe un plugin que nos permite utilizarlo en TailwindCSS. Sin embargo, añadir este plugin como dependencia para solucionar un caso específico puede no ser la mejor opción, ya que estaríamos aumentando el número de dependencias y, por lo tanto, el tamaño de nuestro proyecto. Por lo tanto, hemos optado por buscar una solución que no requiera la utilización de este plugin.

2023-05-01 07:18 UTC, Zyruks commented on apps/nextjs/src/components/DottedBackground/DottedBackground.tsx
> +   */
Listo!

2023-05-01 07:55 UTC, Zyruks commented on apps/nextjs/src/components/DottedBackground/DottedBackground.tsx
> +}
Mejore los colores, pero aún tengo duda de esta implementación. 

Tal vez en la mañana tenga mejores ideas.

![image](https://user-images.githubusercontent.com/14036522/235425680-f4ae2091-83c8-4777-b658-10e44bf734d3.png)

2023-05-01 07:57 UTC, Zyruks commented on apps/nextjs/src/components/DottedBackground/DottedBackground.tsx
> +enum Color {
Sigo tendiendo dudas sobre esta implementación.

Ya veré en la mañana como lo trabajaría.

2023-05-01 07:58 UTC, Zyruks commented on apps/nextjs/src/components/DottedBackground/DottedBackground.tsx
> +}
Done

2023-05-02 07:38 UTC, Zyruks commented on apps/nextjs/src/components/DottedBackground/DottedBackground.tsx
> +}
## Update colors
Ahora obtenemos los colores por default de TailwindCSS y si extendemos también los incluye

![Code_k8mnytHmir](https://user-images.githubusercontent.com/14036522/235607302-1afac7b9-6b82-427f-852a-720abd7614f3.gif)

![image](https://user-images.githubusercontent.com/14036522/235606952-dcffd098-750d-4057-98e0-aebd33fbd60f.png)

2023-05-04 00:22 UTC, serudda approved these changes

2023-05-04 00:23 UTC, merged